Repository Team-Packman/Packman-Server-Spring, pull requests merged in 2023-02, with the labels that each got.

#16 feat: 혼자 패킹리스트 짐 생성 API
  src/main/java/packman/controller/aloneList/AloneListPackController.java
  src/main/java/packman/dto/category/CategoryResponseDto.java
  src/main/java/packman/dto/list/ListResponseMapping.java
  src/main/java/packman/dto/pack/PackCreateDto.java
  src/main/java/packman/entity/Category.java
  src/main/java/packman/entity/Pack.java
  src/main/java/packman/repository/packingList/PackingListRepository.java
  src/main/java/packman/service/aloneList/AloneListCategoryService.java
  src/main/java/packman/service/aloneList/AloneListPackService.java
  src/main/java/packman/util/ResponseCode.java
  src/main/java/packman/validator/IdValidator.java
  src/main/java/packman/validator/LengthValidator.java
  src/main/java/packman/validator/Validator.java
Labels: Enhancement⭐, POST📦, 현지👻

#17 feat: 혼자 패킹리스트 짐 수정 API
  src/main/java/packman/controller/aloneList/AloneListPackController.java
  src/main/java/packman/dto/list/ListResponseMapping.java
  src/main/java/packman/dto/pack/PackUpdateDto.java
  src/main/java/packman/entity/Pack.java
  src/main/java/packman/repository/packingList/PackingListRepository.java
  src/main/java/packman/service/aloneList/AloneListPackService.java
  src/main/java/packman/util/ResponseCode.java
  src/main/java/packman/validator/IdValidator.java
  src/main/java/packman/validator/Validator.java
Labels: Enhancement⭐, PATCH✂, 현지👻

#22 feat: 혼자 패킹리스트 짐 삭제 API
  src/main/java/packman/controller/aloneList/AloneListPackController.java
  src/main/java/packman/service/aloneList/AloneListPackService.java
  src/main/java/packman/util/ExceptionHandler.java
  src/main/java/packman/util/ResponseCode.java
  src/main/java/packman/validator/Validator.java
Labels: Enhancement⭐, DELETE💥, 현지👻

#23 feat: 함께 패킹리스트 짐 생성 API
  src/main/java/packman/controller/aloneList/AloneListPackController.java
  src/main/java/packman/controller/togetherList/TogetherListPackController.java
  src/main/java/packman/repository/FolderRepository.java
  src/main/java/packman/service/PackService.java
  src/main/java/packman/service/aloneList/AloneListPackService.java
  src/main/java/packman/service/togetherList/TogetherListPackService.java
  src/main/java/packman/util/ResponseCode.java
  src/main/java/packman/validator/IdValidator.java
  src/main/java/packman/validator/Validator.java
Labels: Enhancement⭐, POST📦, 현지👻

#24 feat: 함께 패킹리스트 짐 수정 API
  src/main/java/packman/controller/togetherList/TogetherListPackController.java
  src/main/java/packman/service/PackService.java
  src/main/java/packman/util/ResponseCode.java
Labels: Enhancement⭐, PATCH✂, 현지👻

#18 feat: 함께 패킹리스트 카테고리 생성 api
  src/main/java/packman/controller/togetherList/TogetherListCategoryController.java
  src/main/java/packman/service/aloneList/AloneListCategoryService.java
  src/main/java/packman/service/togetherList/TogetherListCategoryService.java
  src/main/java/packman/util/ResponseCode.java
  src/main/java/packman/validator/DuplicatedValidator.java
  src/main/java/packman/validator/LengthValidator.java
Labels: Enhancement⭐, POST📦, 경린🐣

#19 feat: 혼자 패킹 리스트 카테고리 수정 api
  src/main/java/packman/controller/aloneList/AloneListCategoryController.java
  src/main/java/packman/dto/category/CategoryUpdateDto.java
  src/main/java/packman/entity/packingList/PackingList.java
  src/main/java/packman/service/aloneList/AloneListCategoryService.java
  src/main/java/packman/service/togetherList/TogetherListCategoryService.java
  src/main/java/packman/util/ResponseCode.java
  src/main/java/packman/validator/DuplicatedValidator.java
Labels: Enhancement⭐, PATCH✂, 경린🐣

#26 feat: 유저 정보 수정 API
  src/main/java/packman/controller/UserController.java
  src/main/java/packman/dto/user/UserUpdateDto.java
  src/main/java/packman/service/UserService.java
  src/main/java/packman/util/ResponseCode.java
  src/main/java/packman/validator/IdValidator.java
  src/main/java/packman/validator/LengthValidator.java
Labels: Enhancement⭐, PATCH✂, 경린🐣

#27 feat: 혼자 패킹리스트 생성 API
  build.gradle
  src/main/java/packman/controller/aloneList/AloneListController.java
  src/main/java/packman/dto/list/AloneListResponseDto.java
  src/main/java/packman/dto/list/ListCreateDto.java
  src/main/java/packman/entity/FolderPackingList.java
  src/main/java/packman/entity/packingList/AlonePackingList.java
  src/main/java/packman/entity/packingList/PackingList.java
  src/main/java/packman/entity/template/Template.java
  src/main/java/packman/entity/template/TemplateCategory.java
  src/main/java/packman/repository/FolderRepository.java
  src/main/java/packman/repository/packingList/AlonePackingListRepository.java
  src/main/java/packman/repository/template/TemplateCategoryRepository.java
  src/main/java/packman/repository/template/TemplateRepository.java
  src/main/java/packman/service/aloneList/AloneListService.java
  src/main/java/packman/util/ResponseCode.java
  src/main/java/packman/validator/IdValidator.java
  src/main/java/packman/validator/Validator.java
Labels: Enhancement⭐, POST📦, 서희🥑

#28 feat: 함께 패킹리스트 생성 API
  build.gradle
  src/main/java/packman/controller/togetherList/TogetherListController.java
  src/main/java/packman/dto/list/TogetherListDto.java
  src/main/java/packman/dto/list/TogetherListResponseDto.java
  src/main/java/packman/entity/FolderPackingList.java
  src/main/java/packman/entity/UserGroup.java
  src/main/java/packman/entity/packingList/AlonePackingList.java
  src/main/java/packman/entity/packingList/PackingList.java
  src/main/java/packman/entity/packingList/TogetherAlonePackingList.java
  src/main/java/packman/entity/packingList/TogetherPackingList.java
  src/main/java/packman/repository/FolderRepository.java
  src/main/java/packman/repository/packingList/TogetherPackingListRepository.java
  src/main/java/packman/service/togetherList/TogetherListService.java
  src/main/java/packman/util/ResponseCode.java
  src/main/java/packman/validator/IdValidator.java
  src/main/java/packman/validator/Validator.java
Labels: Enhancement⭐, POST📦, 서희🥑

#40 feat: 패킹리스트 날짜, 제목 조회 API
  src/main/java/packman/controller/ListController.java
  src/main/java/packman/dto/list/ListResponseDto.java
  src/main/java/packman/repository/packingList/AlonePackingListRepository.java
  src/main/java/packman/service/ListService.java
  src/main/java/packman/util/ResponseCode.java
  src/main/java/packman/validator/IdValidator.java
Labels: Enhancement⭐, GET🔮, 경린🐣

#44 feat: 템플릿 상세 조회 API
  src/main/java/packman/controller/TemplateController.java
  src/main/java/packman/dto/folder/FolderUpdateRequestDto.java
  src/main/java/packman/dto/template/TemplateCategoryMapping.java
  src/main/java/packman/dto/template/TemplatePackInfo.java
  src/main/java/packman/dto/template/TemplateResponseDto.java
  src/main/java/packman/dto/template/TemplateResponseMapping.java
  src/main/java/packman/repository/template/TemplateRepository.java
  src/main/java/packman/service/TemplateService.java
  src/main/java/packman/util/ResponseCode.java
  src/main/java/packman/validator/Validator.java
Labels: Enhancement⭐, GET🔮, 경린🐣

#29 feat: 혼자 패킹리스트 삭제 API
  src/main/java/packman/controller/aloneList/AloneListController.java
  src/main/java/packman/entity/packingList/PackingList.java
  src/main/java/packman/repository/FolderPackingListRepository.java
  src/main/java/packman/repository/packingList/AlonePackingListRepository.java
  src/main/java/packman/repository/packingList/PackingListRepository.java
  src/main/java/packman/service/aloneList/AloneListService.java
  src/main/java/packman/util/ResponseCode.java
  src/main/java/packman/validator/IdValidator.java
  src/main/java/packman/validator/Validator.java
Labels: Enhancement⭐, DELETE💥, 서희🥑

#32 feat: 함께 패킹리스트 삭제 API
  src/main/java/packman/controller/togetherList/TogetherListController.java
  src/main/java/packman/repository/FolderPackingListRepository.java
  src/main/java/packman/repository/FolderRepository.java
  src/main/java/packman/repository/PackRepository.java
  src/main/java/packman/repository/UserGroupRepository.java
  src/main/java/packman/repository/packingList/PackingListRepository.java
  src/main/java/packman/repository/packingList/TogetherAlonePackingListRepository.java
  src/main/java/packman/repository/packingList/TogetherPackingListRepository.java
  src/main/java/packman/service/togetherList/TogetherListService.java
  src/main/java/packman/util/ResponseCode.java
  src/main/java/packman/validator/IdValidator.java
Labels: Enhancement⭐, DELETE💥, 서희🥑

#33 feat: 혼자패킹리스트 상세 조회 API
  src/main/java/packman/controller/aloneList/AloneListController.java
  src/main/java/packman/dto/list/DetailedAloneListResponseDto.java
  src/main/java/packman/repository/FolderPackingListRepository.java
  src/main/java/packman/repository/packingList/PackingListRepository.java
  src/main/java/packman/service/aloneList/AloneListService.java
  src/main/java/packman/util/ResponseCode.java
  src/main/java/packman/validator/IdValidator.java
Labels: Enhancement⭐, GET🔮, 서희🥑

#34 feat: 혼자 패킹 템플릿 리스트 조회 API
  src/main/java/packman/controller/TemplateController.java
  src/main/java/packman/dto/template/TemplateIdTitleMapping.java
  src/main/java/packman/dto/template/TemplateListResponseDto.java
  src/main/java/packman/repository/template/TemplateRepository.java
  src/main/java/packman/service/TemplateService.java
  src/main/java/packman/util/ResponseCode.java
Labels: Enhancement⭐, GET🔮, 서희🥑

#35 feat: 함께 패킹 템플릿 리스트 조회 API
  src/main/java/packman/controller/TemplateController.java
  src/main/java/packman/service/TemplateService.java
  src/main/java/packman/util/ResponseCode.java
Labels: Enhancement⭐, GET🔮, 서희🥑

#42 feat: 함께 패킹리스트 담당자 배정
  src/main/java/packman/controller/togetherList/TogetherListController.java
  src/main/java/packman/dto/togetherList/PackerUpdateDto.java
  src/main/java/packman/repository/PackRepository.java
  src/main/java/packman/repository/UserGroupRepository.java
  src/main/java/packman/repository/packingList/PackingListRepository.java
  src/main/java/packman/repository/packingList/TogetherPackingListRepository.java
  src/main/java/packman/service/aloneList/AloneListService.java
  src/main/java/packman/service/togetherList/TogetherListService.java
  src/main/java/packman/util/ResponseCode.java
  src/main/java/packman/validator/IdValidator.java
  src/main/java/packman/validator/Validator.java
Labels: Enhancement⭐, PATCH✂, 서희🥑

#43 feat: 함께 패킹리스트 상세 조회
  src/main/java/packman/controller/togetherList/TogetherListController.java
  src/main/java/packman/dto/list/DetaildTogetherListResponseDto.java
  src/main/java/packman/repository/UserGroupRepository.java
  src/main/java/packman/repository/packingList/TogetherAlonePackingListRepository.java
  src/main/java/packman/service/togetherList/TogetherListService.java
  src/main/java/packman/util/ResponseCode.java
  src/main/java/packman/validator/IdValidator.java
  src/main/java/packman/validator/Validator.java
Labels: Enhancement⭐, GET🔮, 서희🥑

#45 feat: 패킹리스트 나만의 템플릿 추가 및 업데이트
  src/main/java/packman/controller/ListController.java
  src/main/java/packman/dto/list/TemplateUpdateDto.java
  src/main/java/packman/dto/list/UpdatedTemplateResponseDto.java
  src/main/java/packman/entity/packingList/PackingList.java
  src/main/java/packman/entity/template/Template.java
  src/main/java/packman/entity/template/TemplateCategory.java
  src/main/java/packman/entity/template/TemplatePack.java
  src/main/java/packman/repository/FolderPackingListRepository.java
  src/main/java/packman/repository/packingList/TogetherAlonePackingListRepository.java
  src/main/java/packman/repository/template/TemplateCategoryRepository.java
  src/main/java/packman/repository/template/TemplateRepository.java
  src/main/java/packman/service/ListService.java
  src/main/java/packman/util/ResponseCode.java
  src/main/java/packman/validator/Validator.java
Labels: Enhancement⭐, PATCH✂, 서희🥑

#30 feat: 최근 생성된 리스트 조회 API
  src/main/java/packman/controller/FolderController.java
  src/main/java/packman/dto/list/RecentCreatedListResponseDto.java
  src/main/java/packman/repository/packingList/AlonePackingListRepository.java
  src/main/java/packman/service/FolderService.java
  src/main/java/packman/util/ResponseCode.java
Labels: Enhancement⭐, GET🔮, 현지👻

#36 feat: 함께 패킹 멤버 조회 API
  src/main/java/packman/controller/MemberController.java
  src/main/java/packman/dto/member/MemberAddResponseDto.java
  src/main/java/packman/dto/member/MemberResponseDto.java
  src/main/java/packman/dto/member/MemberUserDto.java
  src/main/java/packman/entity/Group.java
  src/main/java/packman/service/MemberService.java
  src/main/java/packman/service/togetherList/TogetherListService.java
  src/main/java/packman/util/ResponseCode.java
  src/main/java/packman/validator/IdValidator.java
  src/main/java/packman/validator/Validator.java
Labels: Enhancement⭐, GET🔮, 현지👻

#37 feat: 함께 패킹 멤버 삭제 API
  src/main/java/packman/controller/MemberController.java
  src/main/java/packman/repository/packingList/TogetherPackingListRepository.java
  src/main/java/packman/service/MemberService.java
  src/main/java/packman/service/togetherList/TogetherListCategoryService.java
  src/main/java/packman/util/ResponseCode.java
  src/main/java/packman/validator/IdValidator.java
  src/main/java/packman/validator/Validator.java
Labels: Enhancement⭐, DELETE💥, 현지👻

#38 feat: 함께 패킹리스트 짐 삭제 API
  src/main/java/packman/controller/aloneList/AloneListPackController.java
  src/main/java/packman/controller/togetherList/TogetherListPackController.java
  src/main/java/packman/service/PackService.java
  src/main/java/packman/service/aloneList/AloneListCategoryService.java
  src/main/java/packman/util/ResponseCode.java
  src/main/java/packman/validator/Validator.java
Labels: Enhancement⭐, DELETE💥, 현지👻

#39 feat: 혼자 패킹리스트 초대 API
  src/main/java/packman/controller/aloneList/AloneListController.java
  src/main/java/packman/dto/list/InviteAloneListResponseDto.java
  src/main/java/packman/repository/packingList/AlonePackingListRepository.java
  src/main/java/packman/service/aloneList/AloneListService.java
  src/main/java/packman/util/ResponseCode.java
  src/main/java/packman/validator/Validator.java
Labels: Enhancement⭐, GET🔮, 현지👻

#41 feat: 공유된 패킹리스트 조회 API
  src/main/java/packman/controller/ListController.java
  src/main/java/packman/dto/list/InviteListResponseDto.java
  src/main/java/packman/dto/user/PackerInfo.java
  src/main/java/packman/service/ListService.java
  src/main/java/packman/util/ResponseCode.java
  src/main/java/packman/validator/Validator.java
Labels: Enhancement⭐, GET🔮, 현지👻

#47 feat: 카카오 로그인 API
  build.gradle
  src/main/java/packman/auth/CustomUserDetailsService.java
  src/main/java/packman/auth/JwtAuthenticationFilter.java
  src/main/java/packman/auth/JwtTokenProvider.java
  src/main/java/packman/auth/SecurityConfig.java
  src/main/java/packman/controller/AuthController.java
  src/main/java/packman/dto/auth/AuthKakaoRequestDto.java
  src/main/java/packman/dto/auth/KaKaoAccount.java
  src/main/java/packman/dto/auth/KakaoLoginNewUserResponseDto.java
  src/main/java/packman/dto/auth/KakaoLoginResponseDto.java
  src/main/java/packman/dto/auth/KakaoProfileDto.java
  src/main/java/packman/dto/auth/KakaoTokenDto.java
  src/main/java/packman/dto/auth/KakaoUserProfileDto.java
  src/main/java/packman/entity/User.java
  src/main/java/packman/repository/UserRepository.java
  src/main/java/packman/service/AuthService.java
  src/main/java/packman/util/ResponseCode.java
Labels: Enhancement⭐, GET🔮, 현지👻

#48 feat: 임시 userId를 accessToken으로 가져온 id로 변경
  src/main/java/packman/auth/JwtAuthenticationFilter.java
  src/main/java/packman/auth/SecurityConfig.java
  src/main/java/packman/controller/FolderController.java
  src/main/java/packman/controller/ListController.java
  src/main/java/packman/controller/MemberController.java
  src/main/java/packman/controller/TemplateController.java
  src/main/java/packman/controller/UserController.java
  src/main/java/packman/controller/aloneList/AloneListCategoryController.java
  src/main/java/packman/controller/aloneList/AloneListController.java
  src/main/java/packman/controller/aloneList/AloneListPackController.java
  src/main/java/packman/controller/togetherList/TogetherListCategoryController.java
  src/main/java/packman/controller/togetherList/TogetherListController.java
  src/main/java/packman/controller/togetherList/TogetherListPackController.java
Labels: Enhancement⭐, 현지👻

#46 chore: 함께 패킹리스트 상세 조회 response body에서 isMember 삭제
  src/main/java/packman/dto/list/DetaildTogetherListResponseDto.java
  src/main/java/packman/service/togetherList/TogetherListService.java
Labels: POST📦, 서희🥑

#51 feat: accessToken에 따른 분기 처리를 확인하는 로그 추가
  src/main/java/packman/auth/JwtAuthenticationFilter.java
  src/main/java/packman/dto/list/DetaildTogetherListResponseDto.java
  src/main/java/packman/service/togetherList/TogetherListService.java
Labels: 현지👻

#50 feat: 닉네임 프로필 등록
  src/main/java/packman/auth/SecurityConfig.java
  src/main/java/packman/controller/UserController.java
  src/main/java/packman/dto/user/UserCreateDto.java
  src/main/java/packman/dto/user/UserResponseDto.java
  src/main/java/packman/entity/User.java
  src/main/java/packman/service/UserService.java
  src/main/java/packman/util/ResponseCode.java
Labels: Enhancement⭐, POST📦, 서희🥑

#54 feat: 유저 생성 API 및 cors 설정
  src/main/java/packman/auth/SecurityConfig.java
  src/main/java/packman/controller/UserController.java
  src/main/java/packman/dto/user/UserCreateDto.java
  src/main/java/packman/dto/user/UserResponseDto.java
  src/main/java/packman/entity/User.java
  src/main/java/packman/service/UserService.java
  src/main/java/packman/util/ResponseCode.java
Labels: Enhancement⭐, 서희🥑, 현지👻

#55 feat: corsFilter 설정
  src/main/java/packman/auth/CorsFilter.java
  src/main/java/packman/auth/SecurityConfig.java
Labels: 현지👻

#56 fix: corsFilter 설정
  src/main/java/packman/auth/filter/CorsFilter.java
Labels: Bug🐞, 현지👻

#57 feat: cors 허용 url 추가
  src/main/java/packman/auth/filter/CorsFilter.java
Labels: 현지👻

#58 chore: cors 허용 url 수정
  src/main/java/packman/auth/filter/CorsFilter.java
Labels: 현지👻

#59 fix: 여러 url을 originHeader에 등록
  src/main/java/packman/auth/filter/CorsFilter.java
Labels: Bug🐞, 현지👻

#60 fix: 여러 url을 originHeader에 등록
  src/main/java/packman/auth/filter/CorsFilter.java
Labels: Bug🐞, 현지👻

#61 fix: 여러 url을 originHeader에 등록
  src/main/java/packman/auth/filter/CorsFilter.java
Labels: Bug🐞, 현지👻

#62 fix: localhost:3000만 허용하도록 수정
  src/main/java/packman/auth/filter/CorsFilter.java
Labels: Bug🐞, 현지👻

#63 feat: 임시적으로 모든 url 접근 가능하도록 허용
  src/main/java/packman/auth/filter/CorsFilter.java
Labels: 현지👻

#52 feat: 폴더 삭제
  src/main/java/packman/controller/FolderController.java
  src/main/java/packman/entity/Folder.java
  src/main/java/packman/entity/packingList/PackingList.java
  src/main/java/packman/repository/FolderRepository.java
  src/main/java/packman/repository/packingList/TogetherAlonePackingListRepository.java
  src/main/java/packman/service/FolderService.java
  src/main/java/packman/util/ResponseCode.java
  src/main/java/packman/validator/Validator.java
Labels: Enhancement⭐, DELETE💥, 경린🐣, 서희🥑

#64 feat: 유저 탈퇴 api 수정
  src/main/java/packman/repository/FolderRepository.java
  src/main/java/packman/repository/UserRepository.java
  src/main/java/packman/service/FolderService.java
  src/main/java/packman/service/UserService.java
Labels: Enhancement⭐, 현지👻

#69 ci: 실행중인 애플리케이션의 pid를 deploy.log에 기록
  scripts/stop.sh
Labels: 현지👻, CI💫

#70 ci: 실행 중인 pid를 확인하는 경로 변경
  scripts/start.sh
  scripts/stop.sh
Labels: 현지👻, CI💫

#71 ci: nohup배포 전 경로 이동 추가
  scripts/start.sh
Labels: 현지👻, CI💫

#66 feat: 토큰 재발급 API
  build.gradle
  src/main/java/packman/auth/JwtAuthenticationFilter.java
  src/main/java/packman/auth/JwtTokenProvider.java
  src/main/java/packman/controller/AuthController.java
  src/main/java/packman/dto/auth/NewTokenResponseDto.java
  src/main/java/packman/repository/UserRepository.java
  src/main/java/packman/service/AuthService.java
  src/main/java/packman/util/ResponseCode.java
  src/main/java/packman/validator/Validator.java
Labels: Enhancement⭐, GET🔮, 현지👻

#65 feat: 카카오 로그인 선택항목 동의 안했을 때 빈 문자열 처리
  src/main/java/packman/service/AuthService.java
Labels: 현지👻

#67 feat: 함께 패킹 멤버 삭제 path parameter groupId를 통합 listId로 수정
  src/main/java/packman/controller/MemberController.java
  src/main/java/packman/service/MemberService.java
  src/main/java/packman/validator/IdValidator.java
Labels: DELETE💥, 현지👻

#73 fix: 폴더 안 패킹리스트 조회, 최근 생성된 리스트 조회, 짐 생성 버그 해결
  src/main/java/packman/controller/FolderController.java
  src/main/java/packman/repository/CategoryRepository.java
  src/main/java/packman/service/FolderService.java
  src/main/java/packman/service/PackService.java
Labels: Bug🐞, 현지👻

#74 fix: 폴더 안 패킹리스트 조회, 최근 생성된 리스트 조회, 짐 생성 버그 해결
  src/main/java/packman/controller/FolderController.java
  src/main/java/packman/repository/CategoryRepository.java
  src/main/java/packman/service/FolderService.java
  src/main/java/packman/service/PackService.java
Labels: Bug🐞, 현지👻

#75 fix: 함께 패킹 초대 응답 id 수정
  src/main/java/packman/dto/togetherList/TogetherListInviteResponseDto.java
  src/main/java/packman/repository/packingList/TogetherAlonePackingListRepository.java
  src/main/java/packman/service/togetherList/TogetherListService.java
  src/main/java/packman/validator/Validator.java
Labels: Bug🐞
