Repository Team-Packman/Packman-Server-Spring, pull requests merged in 2023-01, with the labels that each got.

#9 feat: 혼자 패킹 카테고리 생성
  src/main/java/packman/controller/aloneList/AloneListCategoryController.java
  src/main/java/packman/dto/category/CategoryCreateDto.java
  src/main/java/packman/dto/category/CategoryInfo.java
  src/main/java/packman/dto/category/CategoryResponseDto.java
  src/main/java/packman/dto/pack/PackInfo.java
  src/main/java/packman/dto/user/PackerInfo.java
  src/main/java/packman/entity/Category.java
  src/main/java/packman/entity/Pack.java
  src/main/java/packman/entity/packingList/PackingList.java
  src/main/java/packman/repository/packingList/PackingListRepository.java
  src/main/java/packman/service/aloneList/AloneListCategoryService.java
  src/main/java/packman/util/ResponseCode.java
Labels: Enhancement⭐, POST📦, 경린🐣

#3 feat: 유저 조회 API
  src/main/java/packman/controller/UserController.java
  src/main/java/packman/dto/user/UserInfoResponseDto.java
  src/main/java/packman/service/UserService.java
  src/main/java/packman/util/ResponseCode.java
Labels: Enhancement⭐, GET🔮, 현지👻

#6 feat: 유저 탈퇴 API
  src/main/java/packman/controller/UserController.java
  src/main/java/packman/entity/User.java
  src/main/java/packman/repository/UserRepository.java
  src/main/java/packman/service/UserService.java
  src/main/java/packman/util/ResponseCode.java
Labels: Enhancement⭐, DELETE💥, 현지👻

#7 feat: 혼자 패킹리스트 폴더 조회 API
  src/main/java/packman/controller/FolderController.java
  src/main/java/packman/dto/folder/AloneFolderMapping.java
  src/main/java/packman/repository/FolderRepository.java
  src/main/java/packman/service/FolderService.java
  src/main/java/packman/util/ResponseCode.java
Labels: Enhancement⭐, GET🔮, 현지👻

#8 feat: 함께 패킹리스트 폴더 조회 API
  build.gradle
  src/main/java/packman/controller/FolderController.java
  src/main/java/packman/dto/folder/FolderIdNameMapping.java
  src/main/java/packman/dto/folder/TogetherFoldersResponseDto.java
  src/main/java/packman/repository/FolderRepository.java
  src/main/java/packman/service/FolderService.java
  src/main/java/packman/util/ResponseCode.java
Labels: Enhancement⭐, GET🔮, 현지👻

#10 feat: 폴더 속 혼자 패킹리스트 조회
  src/main/java/packman/controller/FolderController.java
  src/main/java/packman/dto/category/CategoryPackMapping.java
  src/main/java/packman/dto/folder/AloneListsInFolderResponseDto.java
  src/main/java/packman/dto/list/ListIdDtoMapping.java
  src/main/java/packman/dto/list/ListInFolderDto.java
  src/main/java/packman/dto/pack/PackCountMapping.java
  src/main/java/packman/repository/CategoryRepository.java
  src/main/java/packman/repository/FolderPackingListRepository.java
  src/main/java/packman/repository/FolderRepository.java
  src/main/java/packman/service/FolderService.java
  src/main/java/packman/util/ResponseCode.java
Labels: Enhancement⭐, GET🔮, 현지👻

#11 feat: 폴더 속 함께 패킹리스트 조회
  src/main/java/packman/controller/FolderController.java
  src/main/java/packman/dto/folder/FolderAloneListMapping.java
  src/main/java/packman/dto/folder/TogetherListsInFolderResponseDto.java
  src/main/java/packman/dto/list/ListIdMapping.java
  src/main/java/packman/dto/list/TogetherAloneListMapping.java
  src/main/java/packman/repository/FolderPackingListRepository.java
  src/main/java/packman/repository/packingList/TogetherAlonePackingListRepository.java
  src/main/java/packman/service/FolderService.java
  src/main/java/packman/util/ResponseCode.java
Labels: Enhancement⭐, GET🔮, 현지👻

#4 feat: 폴더 생성 API
  src/main/java/packman/controller/FolderController.java
  src/main/java/packman/dto/folder/FolderRequestDto.java
  src/main/java/packman/dto/folder/FolderResponseDto.java
  src/main/java/packman/entity/Folder.java
  src/main/java/packman/repository/FolderRepository.java
  src/main/java/packman/service/FolderService.java
  src/main/java/packman/util/ResponseCode.java
Labels: Enhancement⭐, POST📦, 경린🐣

#5 feat: 폴더 조회 API
  src/main/java/packman/controller/FolderController.java
  src/main/java/packman/service/FolderService.java
  src/main/java/packman/util/ResponseCode.java
Labels: Enhancement⭐, GET🔮, 경린🐣

#12 feat: 패킹리스트 제목 수정
  build.gradle
  src/main/java/packman/controller/ListController.java
  src/main/java/packman/dto/list/ListTitleRequestDto.java
  src/main/java/packman/dto/list/ListTitleResponseDto.java
  src/main/java/packman/repository/FolderPackingListRepository.java
  src/main/java/packman/repository/packingList/PackingListRepository.java
  src/main/java/packman/service/ListService.java
  src/main/java/packman/util/ResponseCode.java
  src/main/java/packman/validator/IdValidator.java
  src/main/java/packman/validator/LengthValidator.java
  src/main/java/packman/validator/Validator.java
Labels: Enhancement⭐, PATCH✂, 서희🥑

#13 feat: 패킹리스트 출발 날짜 수정
  src/main/java/packman/controller/ListController.java
  src/main/java/packman/dto/list/DepartureDateRequestDto.java
  src/main/java/packman/dto/list/DepartureDateResponseDto.java
  src/main/java/packman/entity/packingList/PackingList.java
  src/main/java/packman/service/ListService.java
  src/main/java/packman/util/ResponseCode.java
Labels: Enhancement⭐, PATCH✂, 서희🥑
